import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster, toast } from "sonner";
import Navbar from "@/components/navbar";
import { UserProvider } from "@/contexts/userContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <Toaster richColors position="top-right" />
        <body className={inter.className}>{[children]}</body>
      </UserProvider>
    </html>
  );
}
